# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_61pC-QxFa9GRmwv1RJKk4vdSLGbf8aq
"""

import numpy as np
import pandas as pd

df = pd.read_csv("Titanic.csv")

print(df.head())

print(df.shape)

print(df.columns)

print(df.isnull().sum())

df['age'].fillna(df['age'].mean(),inplace = True)
df["embarked"].fillna("S", inplace=True)
df.dropna(inplace=True)

print(df.groupby('sex')["survived"].mean())

df['family_size'] = df["sibsp"] + df["parch"]
print(df.head())

df.to_csv("CleanedDataset.csv")

import seaborn as sns
import matplotlib.pyplot as plt

survival_rate = df["survived"].value_counts(normalize=True)*100
survival_rate.plot(kind="bar")
plt.title("Survival Percentage")
plt.ylabel("Percentage")
plt.show()

sns.barplot(x="sex", y="survived", data = df)
plt.title("Survival Rate by Gender")
plt.show()

sns.boxplot(x="pclass", y="fare", data=df)
plt.title("Fare Distribution by Class")
plt.show()

# df["Family_size"]=df["SibSp"] + df["Parch"]
sns.barplot(x="family_size", y="survived", data=df)
plt.title("Survival Rate by Family Size")
plt.show()

sns.histplot(df["age"],color="yellow")
plt.title("Age Distribution")
plt.show()

sns.histplot(x="age", hue="survived",data=df, palette=["green","blue"],bins=15)
plt.title("Age Distribution by Survival")
plt.show()

Survival = df["survived"].value_counts()
plt.pie(Survival, labels=["Not Survived","Survived"])
plt.title("Survival Pencentage")
plt.show()

sns.scatterplot(x="age", y="fare", data=df)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn .linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

df["embarked"].fillna("S", inplace=True)

df.drop(["class","who","adult_male","deck","embark_town","alive"], axis = 1, inplace=True)

df["sex"] = df["sex"].map({"Male":0, "Female":1})
df["embarked"] = df["embarked"].map({"S":0, "C":1, "Q":2})
df["alone"] = df["alone"].map({True:1,False:0})
df.fillna(0, inplace=True)

x = df.drop("survived", axis = 1)
y = df["survived"]

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=67
)

model = LogisticRegression(max_iter = 1000)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
sns.heatmap(conf_matrix, annot = True, fmt="d")
plt.title("Confusion Matrix")
plt.show()